/*
 *  * C error define file for facility CUPID (1960)
 *   * Generated by the MESSGEN utility
 *    */

#ifndef CUPID_ERROR_DEFINED
#define CUPID_ERROR_DEFINED

/* Too many ClumpFind contour levels */
enum { CUPID__CFCNT           	= 262703458 };	/* messid=300 */

/* Insufficient good values */
enum { CUPID__FWVAL           	= 262703466 };	/* messid=301 */

#endif	/* CUPID_ERROR_DEFINED */
