/*
 * C error define file for facility MSG (103)
 * Generated by the MESSGEN utility
 */

#ifndef MSG_ERROR_DEFINED
#define MSG_ERROR_DEFINED

/* Error encountered during message output. */
enum { MSG__OPTER           	= 141002306 };	/* messid=200 */

/* Error encountered during message synchronisation. */
enum { MSG__SYNER           	= 141002314 };	/* messid=201 */

/* Invalid conditional message filter value. */
enum { MSG__INVIF           	= 141002322 };	/* messid=202 */

/* Invalid tuning parameter name (improper use of MSG_TUNE). */
enum { MSG__BDPAR           	= 141002330 };	/* messid=203 */

/* Bad tuning value (improper use of MSG_TUNE). */
enum { MSG__BTUNE           	= 141002338 };	/* messid=204 */

/* Bad MSG environment variable value. */
enum { MSG__BDENV           	= 141002346 };	/* messid=205 */

/* Fatal internal error. */
enum { MSG__FATAL           	= 141002354 };	/* messid=206 */

#endif	/* MSG_ERROR_DEFINED */
